use std::fs;
use std::path::Path;

use crate::config::Paths;
use crate::core::WebServerConfig;
use crate::error::{Error, Result};
use crate::utils::{execute_command, log_info, log_verbose};

pub struct NginxConfig;

impl NginxConfig {
    pub fn new() -> Self {
        NginxConfig
    }

    fn default_template(domain: &str, port: u16) -> String {
        format!(
            r#"# Generated by localstacker
# Domain: {domain}
# Backend: 127.0.0.1:{port}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    
    # Redirect all HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    # SSL Configuration
    ssl_certificate     /etc/nginx/ssl/{domain}.pem;
    ssl_certificate_key /etc/nginx/ssl/{domain}-key.pem;
    
    # SSL Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Logging
    access_log /var/log/nginx/{domain}_access.log;
    error_log /var/log/nginx/{domain}_error.log;

    # Proxy Configuration
    location / {{
        proxy_pass http://127.0.0.1:{port};
        
        # Proxy Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
        
        # WebSocket Support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Buffering
        proxy_buffering on;
        proxy_buffer_size 4k;
        proxy_buffers 8 4k;
        proxy_busy_buffers_size 8k;
    }}
}}
"#,
            domain = domain,
            port = port
        )
    }
}

impl WebServerConfig for NginxConfig {
    fn generate_config(&self, domain: &str, port: u16, template: Option<&str>) -> Result<String> {
        log_verbose(&format!("Generating nginx config for {}", domain));

        if let Some(template_path) = template {
            // Load custom template
            let template_content = fs::read_to_string(template_path)
                .map_err(|e| Error::Config(format!("Failed to read template: {}", e)))?;

            // Simple variable replacement
            let config = template_content
                .replace("{{domain}}", domain)
                .replace("{{port}}", &port.to_string());

            Ok(config)
        } else {
            Ok(Self::default_template(domain, port))
        }
    }

    fn write_config(&self, domain: &str, config: &str) -> Result<()> {
        log_info(&format!("Writing nginx configuration for {}...", domain));

        let config_path = Paths::nginx_config(domain);
        
        if Path::new(&config_path).exists() {
            // replace existing config
            fs::write(&config_path, config)
                .map_err(|e| Error::Config(format!("Failed to write nginx config: {}", e)))?;   
            // return Err(Error::Already(format!(
            //     "Nginx config for {} already exists",
            //     domain
            // )));
        }

        fs::write(&config_path, config)
            .map_err(|e| Error::Config(format!("Failed to write nginx config: {}", e)))?;

        Ok(())
    }

    fn enable_site(&self, domain: &str) -> Result<()> {
        log_info(&format!("Enabling site {}...", domain));

        let available = Paths::nginx_config(domain);
        let enabled = Paths::nginx_enabled(domain);

        if Path::new(&enabled).exists() {
            log_verbose("Site already enabled");
            return Ok(());
        }

        #[cfg(unix)]
        std::os::unix::fs::symlink(&available, &enabled)
            .map_err(|e| Error::Config(format!("Failed to enable site: {}", e)))?;

        Ok(())
    }

    fn disable_site(&self, domain: &str) -> Result<()> {
        log_info(&format!("Disabling site {}...", domain));

        let enabled = Paths::nginx_enabled(domain);

        if !Path::new(&enabled).exists() {
            log_verbose("Site already disabled");
            return Ok(());
        }

        fs::remove_file(&enabled)
            .map_err(|e| Error::Config(format!("Failed to disable site: {}", e)))?;

        Ok(())
    }

    fn test_config(&self) -> Result<()> {
        log_info("Testing nginx configuration...");
        execute_command("nginx", &["-t"], "Test nginx config")?;
        Ok(())
    }

    fn reload(&self) -> Result<()> {
        log_info("Reloading nginx...");
        execute_command("systemctl", &["reload", "nginx"], "Reload nginx")?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_template_contains_domain() {
        let config = NginxConfig::default_template("test.local", 3000);
        assert!(config.contains("test.local"));
        assert!(config.contains("127.0.0.1:3000"));
    }
}